// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz3MAJQ1HcrXFCJ9XLkPiOJFXtqsSg9ms',
    appId: '1:643052666941:web:ac4588e10491b9fe362a54',
    messagingSenderId: '643052666941',
    projectId: 'motion-6b0c9',
    authDomain: 'motion-6b0c9.firebaseapp.com',
    storageBucket: 'motion-6b0c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6xp0YiKYCaVUc6RihzaVdJggWeikTS9s',
    appId: '1:643052666941:android:cb3ed78f1301be32362a54',
    messagingSenderId: '643052666941',
    projectId: 'motion-6b0c9',
    storageBucket: 'motion-6b0c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC1pTOkegf7Oo2Ah2e1xFvJ9aAllFcpSo',
    appId: '1:643052666941:ios:4db925ae6ef0f126362a54',
    messagingSenderId: '643052666941',
    projectId: 'motion-6b0c9',
    storageBucket: 'motion-6b0c9.appspot.com',
    iosClientId: '643052666941-4vudhbevtc05mlpgkmohp45a4lmf31pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudMotion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC1pTOkegf7Oo2Ah2e1xFvJ9aAllFcpSo',
    appId: '1:643052666941:ios:4db925ae6ef0f126362a54',
    messagingSenderId: '643052666941',
    projectId: 'motion-6b0c9',
    storageBucket: 'motion-6b0c9.appspot.com',
    iosClientId: '643052666941-4vudhbevtc05mlpgkmohp45a4lmf31pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudMotion',
  );
}
